### PR TITLE
Modify scripts to include all SSPs

### PR DESCRIPTION
**Pull request by leeyap**
Hi @bpbond,

This initial code (work in progress!) reworks my existing scripts so that Hector can be run in multiple scenarios. This might not be the most efficient way to do this, but it works and does not majorly increase computation time.

There are quite a few little tweaks that I made to get this to work, but the major changes are as follows:
- There are now two run lists, `runlist_scenarios` and `runlist_main`. The first contains `N_RUNS_SCE` runs [I used 100 for now] for all specified scenarios, and the second contains `N_RUNS_MAIN` runs of _just_ the main scenario, defined in the `trackingC_common.R` file.
- The first 100 runs contain the same parameter distributions, so for example, run 1 has the same combination of parameter values across all scenarios. 
- The run loop is now a nested for loop. First, it loops over each scenario and initiates a new core. Then, it applies `run_hector()` as it did before, and shuts down the core at the end. 

I started to tackle redoing some figures. I was able to run the CMIP6 temperature comparison diagnostic and filter out bad runs by scenario. Which figures would be most useful to modify to include all the SSPs? I think definitely the airborne fraction and the destination fraction graphs, and the relative importance one. 

Comments and feedback appreciated, as always. Happy to go over the changes, too. Thanks!

### CODE REVIEW

**Comment by leeyap** [comment]
Small comment on new method - previously, each run had a run number of 1-100 (or whatever) and only SSP245 had 101-1000. The reason that I did it like that was so that across each run number (1-100), the parameter values were the same, so it was easy to compare outputs across scenarios, holding the parameters constant. I'm not sure if this is something we want to preserve.

**Comment by leeyap** [comment]
Small comment on new method - previously, each run had a run number of 1-100 (or whatever) and only SSP245 had 101-1000. The reason that I did it like that was so that across each run number (1-100), the parameter values were the same, so it was easy to compare outputs across scenarios, holding the parameters constant. I'm not sure if this is something we want to preserve.

**Comment by bpbond** [comment]
@leeyap A couple of problems — one 100% MY FAULT 😬 and the other due to Kalyn's output-renaming changes. Pushed a fix!

**Comment by leeyap** [comment]
@bpbond thank you!

**Comment by bpbond** [comment]
@leeyap It looks like your last commit [a0ed50d](https://github.com/JGCRI/trackingC/pull/38/commits/a0ed50dbe3299e2148a4346b9071f3ee0e4040f9) broke a lot of things—there now are duplicate chunk labels, incorrect figure captions, and a broken `facet_wrap` in line 227. FYI!

**Comment by bpbond** [comment]
Also I see
```r
# Just looking at 5 random runs across scenarios
### THIS NO LONGER WORKS
dest_runs <- ffi_destinations %>%
  group_by(ssp) %>%
  filter(year == min(year)) %>%
  slice_sample(n = 5) %>%
 ```

😕 

One potential problem is that you can't `slice_sample` more runs than are present. Possible fix:
```r
  slice_sample(n = min(100, n())) %>%
```

**Comment by leeyap** [comment]
@bpbond I think this should be just about ready to go!

**Comment by bpbond** [comment]
Woo hoo! Great end to the week. I'm happy to look over if useful, but go for it if you'd like immediate satisfaction :)

**Review by bpbond — APPROVED** [review]

**Pull request merged**
